### ISSUE TITLE
Bug : Screen freeze when changing track

### ISSUE THREAD

**Issue by garfieldairlines** [victoralvesf/aonsoku#192]
I don't know how to properly report that but on Linux when playing TF2 I get Aonsoku making my screen crash for a second when changing tracks.

I will gladly provide you logs but I don't know on which end the logs are supposed to be.

(Using aonsoku-bin 0.9.1-1 on the Arch AUR repo)

**Comment by victoralvesf** [comment]
@garfieldairlines, thanks for reporting this issue. The current version uses Tauri to generate the desktop app, and on Linux, the web engine is Webkit2GTK, which has proven to be quite problematic.

I'm currently working on migrating to Electron. While it may consume more disk space and RAM, it will provide a much smoother experience. This change will also allow me to reintroduce features that were previously disabled on Linux due to compatibility issues with Webkit2GTK, among other improvements.

There are still a few things I need to implement, but overall, it's mostly ready for release.

**Comment by victoralvesf** [comment]
I think this problem was fixed in the latest release [v0.10.2](https://github.com/victoralvesf/aonsoku/releases/tag/v0.10.2).

**Comment by garfieldairlines** [comment]
Thanks, I'll give it a shot when it gets updated in the AUR !

**Comment by garfieldairlines** [comment]
I tried it out when hitting "next track" I still get the freezes but they are much shorter.
